name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Roda todo dia à meia-noite UTC

  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: Joseamorim22
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit e push do arquivo gerado
        run: |
          mkdir -p dist
          mv github-contribution-grid-snake.svg dist/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizando a cobrinha"
          git push
